### ISSUE TITLE
Cannot play MJPEG stream

### ISSUE THREAD

**Issue by kolyneh** [dburckh/Media3Avi#4] opened 2023-02-06 04:02 UTC
Hi, I use this library to play MJPEG stream: [http://webcam1.vilhelmina.se/mjpg/video.mjpg](http://webcam1.vilhelmina.se/mjpg/video.mjpg) but failed.
Log here:
```
internalError [eventTime=8.78, mediaPos=0.00, window=0, period=0, loadError
  androidx.media3.exoplayer.source.UnrecognizedInputFormatException: None of the available extractors (JpegExtractor, FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, AviExtractor, Mp3Extractor, JpegExtractor) could read the stream.
      at androidx.media3.exoplayer.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:101)
      at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1018)
      at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
      at java.lang.Thread.run(Thread.java:923)
]

```

I have used `JpegExtractor` for MJPEG but not working, MJPEG stream's response header is like `Content-Type=[multipart/x-mixed-replace; boundary=myboundary]` that's a multipart response.

Looks like we are missing a `MJpegExtractor` to handle this.

**Comment by dburckh** [comment] 2023-02-06 20:20
This is out of the scope of AVI, but if someone created a MultiPartExtractor my BitmapFactoryVideoRenderer should be able to render it.  It would be pretty straightforward as the HTTP stream from your camera is just:

\r\n--myboundary
\r\nContent-Type: image/jpeg
\r\nContent-Length: 156227
\r\n
\r\n
{JPEG Data}

If you want to spin up a new project, I can help you out.

**Comment by kolyneh** [comment] 2023-02-09 08:41
Thank you,
I have created my MultiPartExtractor , and try to reuse the `JpegExtractor` in it.
But this `JpegExtractor` can just sniff  Motion Photo.

**Comment by dburckh** [comment] 2023-02-09 17:18
Using JpegExtractor is probably overkill, I would start from scratch.  Generally parsing the stream is going to involve looking for two sequences of bytes the HEADER_START, "\r\n\--" and the HEADER_END, "\r\n\r\n\".  Once you get that you can convert it to a String and parse it out.

Your most import methods are init(), sniff(), read() and seek().

init()

Copy/Paste from JpegExtractor.

sniff()

1. Since the header is variable size, I would I would have sniff() peek up to 128 bytes, looking for HEADER_START and HEADER_END.  Media3 imports Guava, so you can use Bytes.indexOf().  FYI:  I usually use Knuth–Morris–Pratt for these searches, but I digress.
2. Convert the everything from [HEADER_START, HEADER_END] to String
3. Using a BufferedReader loop through the lines and looks for "Content-Type: image/jpeg".  If you find it, you return true.

read()

1.  Using the ExtractorOutput from init(), create a TrackOutput like JpegExtractor.outputImageTrack().  Only do this once!
2.  Using code similar to sniff(), peak in the header and convert it to a String
3. This time you want parse out of the value of HttpHeaders.CONTENT_LENGTH
4. Once you get the value, send that many bytes, skipping the header, to the TrackOutput you created.

seek()

Probably don't want to mess with this.  :)

**Comment by kolyneh** [comment] 2023-02-10 16:20
🥲
Really a mess.
I tried what you said but failed, nothing is showing up.

Here is what I did for MultiPartExtractor,
I'm not familiar with codecs though:
[https://github.com/kolyneh/media3-mjpeg](https://github.com/kolyneh/media3-mjpeg)

And I tried to create a `JpegStillImageExtractor ` to show jpeg still image, but not working. 
ExoPlayer created a `ProgressiveMediaSource` for most of the video file types, not for images.
![image](https://user-images.githubusercontent.com/13062910/218141337-f6dfbd25-897b-4a20-a5b1-162c2be1ea0a.png)

**Comment by dburckh** [comment] 2023-02-12 17:51
Very nice.  You were sooo close.  I attached the patches with the fixes.  Overview:

1. You need to tell Exo you are done adding tracks.  Easy peasy fix.
2. Exo requires you to send metadata.  You had the call, then removed it.  There was also a minor bug in call.  The offset generally should be 0.  This should only be non zero if you sent multiple frames and you want to set the PTS retroactively.  

Notes:

- You should generally not use System.currentTimeMillis() because it can adjust when the device time is adjusted from the network.
- Exo buffers about 500ms of video by default.  You may want to defeat this because the video is real time.
- If you make me a contributor, I can do a proper PR.

[Fixes_for_MultiPartExtractor.patch](https://github.com/dburckh/Media3Avi/files/10716769/Fixes_for_MultiPartExtractor.patch)

**Comment by kolyneh** [comment] 2023-02-13 02:14
Thanks! With your patch now it is working!
I have invited you as contributor.

But as you said the video is not playing in real time now.  I'm trying to defeat this.

**Comment by dburckh** [comment] 2023-02-13 16:18
I haven't worked much with live video.  Here is the old ExoPlayer link on Live Video.  https://exoplayer.dev/live-streaming.html

It looks like the Demo creates the MediaItem in IntentUtil.createMediaItemFromIntent().

For one of my apps I use Exo to generate thumbsnails for on device files.  In that case I drop the buffer way down (see code).  I think the MediaItem approach is better, but this might work as a quick and dirty hack.

        final LoadControl loadControl = new DefaultLoadControl.Builder().setBufferDurationsMs(100, 250, 100, 100).build();
        mExoPlayer = new ExoPlayer.Builder(mContext, new VideoOnlyRendersFactory(mContext)).setLoadControl(loadControl).build();

**Comment by kolyneh** [comment] 2023-02-14 10:11
Pretty good.
Use the LoadControl as global setting now it is working great for streaming. 👍 

But for on device files,  it will load all frames immediately then ends the output.
Maybe it is some thing with the SeekMap I haven implemented.

Another issue with streaming is when recovering from a lost connection, the display will be intermittently stuck.
I'm trying to handle this.

**Comment by dburckh** [comment] 2023-02-15 01:50
I don't think it's the SeekMap.  I think the problem is the Extractor uses the current time for the frame time.  That works great for real time because there is a delay between frames.  For device files, they are submitted as fast as they are loaded, so it's queuing all frames with roughly the same time.  Since the device files don't have any timing data, you may need to pass frame time to the Extractor somehow and use that instead of the current time.

**Comment by kolyneh** [comment] 2023-03-13 10:16
Hi, 
I had updated the time handling as you said, it's working, but using the `BitmapFactoryVideoRenderer` to render HD video is laggy. I changed it to use `FFmpeg` to render the frame and now it is playing more smoothly. 
Renderer here thanks for AhmedHumk: [ffmpegVideoDecoder](https://github.com/AhmedHumk/ffmpegVideoDecoder)

I think the most time/cpu cost is the bitmap decoding and KMP searching(for searching next frame). Though using FFmpeg to render can reduce time consumption, the cpu usage is higher, and the KMP search will take more time when the frame size increases. 

Some device may have `video/mjpeg` codec, but little.

My next step is :

- Reduce cpu usage when using software renderer.
- Reduce time cost for searching frames for local file.

Do you have any advice on this two?

**Comment by dburckh** [comment] 2023-03-13 22:31
- Unfortunately, you are stuck with the high CPU usage as almost every device uses software decoding for JPEG.  Nvidia has some chipsets that support hardware decoding, but it's rare.  Those chipsets might just work out of the box in Exo, but I've never tried it.  :)
- The KMPSearch should be fairly negligible.  The only exception would be if the HTTP header didn't have the content-length, then you would have to scan the whole stream.  If that becomes a sticking point, I have some options...

I'm surprised that ffmpeg is outperforming BitmapFactory.  There was an Android change request to port libjpeg/libjpegturbo (used in ffmpeg) into Android and they discovered that usually skia (BitmapFactory) was slightly faster.  There might be a bug in my code or maybe something changed?  Most of the AVI/MJPEG videos I've used are from older point and shoot cameras, which are at lower resolutions.

- What kind of resolutions are you decoding and at what frame rate were you seeing slow downs?  I've done a lot of JPEG decoding testing in another app and I can decode 1080p@30fps without issue.  Even low end stuff can do 720p@30fps.  I could see 1080p@60fps creating problems for BitmapFactory.
- Also what phone are you using?

**Comment by kolyneh** [comment] 2023-03-14 09:52
I have updated my project: [media3-mjpeg](https://github.com/kolyneh/media3-mjpeg).
You can download sample media files here: [https://filesamples.com/formats/mjpeg](https://filesamples.com/formats/mjpeg)
The KMP Search is now only use on local file because the local file is just jpeg sequence, no headers within.

I'm using a Snapdragon 730G tablet for test.
Here's the result:

1080p@30fps
- FFmpeg renderer:  5%~6% cpu usage.
- BitmapFactory renderer:  11%~12% cpu usage. In `renderBitmap` method log deltaRenderTime sometimes greater than 30ms.

4K@30fps
- FFmpeg renderer:  20%~22% cpu usage.
- BitmapFactory renderer:  Can not render because `isFrameLate` return true.

**Comment by dburckh** [comment] 2023-03-14 15:38
Thanks for all the info.  Questions:

- What are you using to create the .mjpeg files?  When I used VLC to save the raw streams, I was getting the headers.  Here is a sample I created using VLC:  https://drive.google.com/file/d/1GAtDIX2QlHj0G9Fq8DhT-K1Dq9v-D3M4/view?usp=share_link
- I don't see a KMPSearch anywhere.  Maybe I'm missing something?  Here is what I mean by KMP Search:  https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/

Thoughts:

- Looking at how AhmedHumk did his FfmpegDecoder, I did things the hard way.  :)  I'll try to re-write my stuff to use SimpleDecoder and DecoderVideoRender that may help the performance.  I'm travelling some of this week, so it may be a bit.
- It's odd that renderBitmap() is the bottleneck.  I would expect it to be DecoderRunnable.run().  Maybe Exo is forcing the Surface frame rate?  The change above could fix that.
- Ffmeg has a couple of advantages over the BitmapFactory (Java) method.  It can bypass the Bitmap step (and overhead) and it can draw directly to the Surface.  I won't ever be able to improve on that.  :(

**Comment by dburckh** [comment] 2023-03-14 22:11
I rewrote the BitmapFactoryVideoRenderer as BitmapFactoryVideoRenderer2 and pushed it to a branched called bitmapFactory2 in your repo.  It's now using the same Exo base classes as FFMpegVideo.  I didn't see how to enable FFMpegVideoDecoder, so I couldn't get timings from that.

Results - Using sample_3840x2160.mjpeg:
- On my Note S20, it played flawlessly at about 20% utilization, decoding was floating around 30ms and rendering was around 1ms.  Decoding time was right a framerate, so it was probably borderline.  
- On my Pixel 3a, it only showed the first image and the video froze, but decoding was taking 90ms per image.
- Definitely an improvement, but there could be some other optimization.  I've tried parallelizing JPEG decoding on Android, but haven't had a ton of luck.

Other stuff:
- I see there is stuff listed as mjpeg with audio.  Do you know what the spec for that is?  If what was possible and it would play in Chrome, I would be very interested.
- I'm AssUMe-ing that FFMpeg is using libjpeg/turbo.  I looked at Skia and it has options to use libjpeg/turbo.  I can't say as to whether they are turned on in Android.

**Comment by kolyneh** [comment] 2023-03-15 15:25
As you might know the mjpeg files I used for test is from [https://filesamples.com/formats/mjpeg](https://filesamples.com/formats/mjpeg), which may be converted by FFmpeg. (Yes, it generated the wired Jpeg format without JFIF marker, instead a commont with "Lavc" from libavc).

And the KMPSearch class name is `KMPMatch`. https://github.com/kolyneh/media3-mjpeg/blob/e0560493d43141c73826b8f8d795ffd7dde90f88/libraries/extractor/src/main/java/androidx/media3/extractor/mjpeg/KMPMatch.java

I have added `FFmpeg` as a submodule to project root and pushed to `ft/mjpeg-ffmpeg-renderer` branch. You can check it out to build ffmpeg then run with FFmpegVideoRenderer enabled.
Steps:
- cd to FFmpeg folder.
- checkout a version for example  `release/4.2`.
- follow this [https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg) to build `ffmpeg` for Android.(Checking out ffmepg can be skipped because we've done above two steps.)
- then run the demo.
- check that FFmpegVideoRenderer is loaded in `DefaultRenderersFactory#buildVideoRenderers`.

For Skia, may be it's use in the render phrase instead of the decode phrase? I don’t know about that.

Anyway,
thanks a lot for your great help!

**Comment by kolyneh** [comment] 2023-03-15 15:35
For the mjpeg file with audio, I haven’t found a player can play the sound track..😂

**Comment by dburckh** [comment] 2023-03-16 14:40
> For the mjpeg file with audio, I haven’t found a player can play the sound track..😂

Yeah, I didn't think it was valid to have audio in mjpeg.  It was confusing.

**Comment by dburckh** [comment] 2023-03-16 15:21
Something appears to be wrong with the submodules checkin.  When I did it for this project, I checked in a submodule stub (link below).  There are two submodules here (LibRaw and LibRaw-CMake).  Notice they are linked to a specific version. I think you need to check in the FFMpeg base folder (just the folder)
https://github.com/dburckh/AndroidLibRaw/tree/master/libraw/src/main/cpp

ft/mjpeg-ffmpeg-renderer was not up to date when I looked at it.  Since bitmapFactory2 was branched off of this, you should be able to merge it in fairly cleanly.

Now that I'm up to date.  Couple of notes on your KMPMatch:
- I noticed you are recomputing the failure condition array every time.  You can compute this once staticly and pass it in.  I've attached my version of KMPMatch for reference.  Feel free to use it.  [KMPMatch.zip](https://github.com/dburckh/Media3Avi/files/10992531/KMPMatch.zip)
- You can compute endMarkerBytes statically as well.  
- ProTip: You can simplify it to this:  static final byte[] END_MARKER_BYTES = {(byte)0xff, (byte)0xd9};

I'm going on vacation, so I'm going to be out of pocket for a few days.

**Comment by kolyneh** [comment] 2023-03-17 08:46
Thanks for your sample and KMPMatch.
I've updated the FFmpeg submodule to link the correct point, and bitmapFactory2 was merged too.
And tested the bitmapFactory2 for playing 4K video, it's frozen too, besides are ok then.
I'll see if something wrong there for the rendering.

Have a great vacation!

**Comment by dburckh** [comment] 2023-03-22 03:37
Alrighty, I finally got ffmpeg to compile and working.  I did reproduce your results.  I was averaging about 19ms per frame(MSPF) at about 14% CPU decoding using FFMpeg and 33 MSPF at about 20% CPU using BitmapFactory.  I changed BitmapFactory to recycle the Bitmap and it improved to about 27 MSPF at about 18% CPU.  The MSPF is averaged over 15 random frames and the CPU is eyeballed, so these numbers are "in the ballpark" at best.

I'm not sure if FFMpeg is faster due to hardware acceleration, ARM Neon Enhancements, lower quality decode or just better code.  I would be curious to compile libjpegturbo and see where the results lie.  For your project, ffmpeg is probably the best choice just because it's easier.

**Comment by dburckh** [comment] 2023-05-01 23:11
So after a month of experimenting and digging around, I figured out how ffmpeg is so much faster than BitmapFactory (libjpeg-turbo).  It turns out that JPEG is usually YUV420, not RGBA.  Android doesn't support a Bitmap using YUV420 (at least not publicly), so it has to convert the YUV420 to RGBA.  That's lossy and has considerable overhead.  ffmpegVideoDecoder decodes to JPEG to YUV420 and draws directly to the screen without conversion.  Way faster.

So, can we beat ffmpegVideoDecoder?  Maybe.  It should be possible to do the same thing directly with libjpeg-turbo. 
 Assuming ffmpeg is not already using libjpeg-turbo, it could be faster.  This is pretty academic discussion at this point, because you already have working solution that is very fast and easy.

**Comment by dburckh** [comment] 2023-06-28 22:01
Closing this as it's interesting, but out of scope.

**Closed as not planned** 2023-06-28 22:01 UTC
